### ISSUE TITLE
Typo: "palced" -> "placed"

### ISSUE THREAD

**Issue by JobLeonard** [kristoff-it/zine-ssg.io#16]
> Any argument can be **palced** between the parenthesis and separated with a `,` (trailing commas are allowed). Arguments can be both literals and other Scripty expressions.

https://github.com/kristoff-it/zine-ssg.io/blob/3f3594744f2a8303da69ef569e2e155d1fd9c28c/content/docs/scripty.smd#L75

(wanted to do a quick edit to save you the trouble but GH was being a bit of a pain about it, so opened an issue instead, sorry)

**Comment by JobLeonard** [comment]
Also congrats on the public release! :)

**Comment by kristoff-it** [comment]
Thanks, fixed the typo just now!
