### ISSUE TITLE
Add suport on .smd and .shtml for Zed Editor

### ISSUE THREAD

**Issue by ikks** [kristoff-it/zine-ssg.io#18]
Thanks for this project, is refreshing to see alternatives with Zig for SSG.  

Please consider adding language support for [Zed Editor](https://zed.dev/docs/extensions/languages), seems that it can be similar to [Helix](https://zine-ssg.io/docs/editors/).

**Comment by kristoff-it** [comment]
Consider doing the inverse: open an issue in the Zed repository to see if the maintainers are interested in using SuperHTML. If they are, ping me, and I will be happy to help.

**Comment by kristoff-it** [comment]
Related https://github.com/zed-industries/zed/issues/18897
